### ISSUE TITLE
[Feature request] trigger "open with" using a keyboard-mouse-click shortcut

### ISSUE THREAD

**Issue by turchinc** [andy-portmen/native-client#1]
Most intuitive keyboard-mouse-click combinations are already assigned, but AFAICT, alt-shift-click to trigger "open with" should be possible? 

https://support.google.com/chrome/answer/157179?hl=en

**Comment by andy-portmen** [comment]
Thanks for the suggestion. "Open in Firefox" version 0.1.4 now supports adding a custom keyboard-mouse-click combination. This feature is disabled by default though. Please give it a try. If this new feature works as expected, we can have it on the other products as well.

**Comment by andy-portmen** [comment]
I believe all open-in extensions (browser openers) now support keyboard-mouse-click combination if it is enabled in the options page. So I am closing this.
