### ISSUE TITLE
Deleting every project host controller base, i dont do this for money 

### ISSUE THREAD

**Issue by MTHEcomposer** [andy-portmen/native-client#111]
hey tinkle bell....... im fucking deleting every project with controller base!! people like yall make open source shitty.... No respect i blame google though stop installing host base projects on my plateform without concent. idgaf if open source or not im deleting have some respect. be professional

**Comment by 4Umedtransit** [comment]
Who Is this and why am I in this email chain? Please assist me in understanding the situation and if somebody is sending these emails as a joke please stop immediately.


Regards,
Joseph R Romero III
844.243.9988
