### ISSUE TITLE
The worrying decline of JavaScript (JS) and jQuery language degrades some performances = what impact will this have on node.js and Native client and Open-in-vlc? and what will be the alternative?

### ISSUE THREAD

**Issue by trimechee** [andy-portmen/native-client#136]
Hello, I found a worrying article about the decline of the javascript language and the performance problems related to librarie JQuery...and many developers are calling to abandon javascript and JQuery to avoid slowness :

"it seems that the fashion for all JavaScript (with, among others, its use in the famous node.js) is fading for the greater performance of websites."

https://javascript.developpez.com/actu/361166/-Nous-devons-arreter-d-utiliser-JavaScript-lance-Douglas-Crockford-le-createur-de-JSON-dont-la-sortie-suggere-que-le-langage-est-devenu-une-usine-a-gaz-apres-une-trentaine-d-annees-d-existence/

Our beloved Native client is linked to nodejs based on javascript, what impact will the catastrophe of the abandonment of javascript by websites have on our beLoved Open-in-vlc please? will it be impossible to use Open-in-vlc if javascript is dead? and is there an alternative to javascript and nodejs please?

**Comment by trimechee** [comment]
Another article : The relentless pursuit of cutting-edge JavaScript frameworks inadvertently contributed to a less accessible web :  

https://www.easylaptopfinder.com/blog/posts/cutting-edge-js-framework-accessibility


https://javascript.developpez.com/actu/361633/-L-utilisation-incessante-de-frameworks-JavaScript-de-pointe-a-contribue-a-rendre-le-Web-moins-accessible-d-apres-Easy-Laptop-Finder-selon-lequel-ces-derniers-detruisent-les-performances-des-sites-Web/

**Comment by andy-portmen** [comment]
This native client doesn't rely on NodeJS itself; it only uses it to launch a native application with specific arguments, similar to how a user would click a desktop icon. After launching, the NodeJS process is terminated. Therefore, updating NodeJS isn't necessary for this extension's functionality. The entire process takes less than a second.

**Comment by trimechee** [comment]
It's reassuring !! I close the issue and thank you very much for these important explanations and for your magnificent life saver software :) 💯 🥇
