### ISSUE TITLE
Catsxp

### ISSUE THREAD

**Issue by trimechee** [andy-portmen/native-client#137]
Hello, really sorry to bother you again Mr @andy-portmen , just to reveal the result of my many experiments and tests, so Open-in-vlc for firefox and chrome are equivalent (i thought that keeping the child process would allow firefox to be compatible with more sites but this is not the case after my tests), the other chromium browsers for windws 7 32 bits are good and use chromium lts but do not use the latest version of chromium kernel except Catsxp browser, the developer of catsxp told me recenly to try the beta version of catsxp for windows 7 32 bits which solved the crash on certain sites in windows 7 32 bits so catsxp becomes the ideal browser for windows 7 32 bits and uses the latest version of chromium and actively developed and we do not need to keep the child process as in firefox = saving battery resources, bandwidth, so please our dream is a specific support for catsxp and registry modification for catsxp which kept the manifest v2 (catsxp seems to be based on the code of brave browser but catsxp bringing several new features and extraordinary original options), and I can use ublock origin manifest v2 in catsxp, I think catsxp becomes the best browser in the world and in addition catsxp is compatible with windows 11 and also updated for windows 7 32 bits with the latest chromium kernel and therefore no need to bother supporting other new web browsers and our dream please it is a specific support of Native client for Catsxp browser, thank you very much!

I made this request because catsxp is objectively the best browser in the world because chrome now told users to stop using ublock origin manifest v2 and to migrate to other ad blocker extensions manifest v3, brave browser is good but brave installed a VPN without the explicit consent of the users and then controversy and the VPN removed..... 

firefox forks are good but keep the child process with Open in vlc = waste of resources, and supermium is excellent but I don't know if supermium browser is compatible with windows 11 and supermium does not use the latest version of chromium = catsxp becomes the best browser in the world hence the importance of adding specific support for this browser please :)

**Comment by andy-portmen** [comment]
Did you have a problem using native-client on this browser? This is a Chrome-based browser, so it is going to support native client as far as I can tell.

**Comment by trimechee** [comment]
No, I didn't encounter any bug with Open-in-vlc in catsxp, I just expressed my fear of possible problems and compatibility....but for now, there is no problem so I close the issue and I will reopen it if I encounter any problems, thank you very much for your help and patience :)

**Comment by trimechee** [comment]
Hi Mr Andy, excuse me but just a question : catsxp disable by default the flag : Auto-disable Accessibility (When accessibility APIs are no longer being requested),

so catsxp permanently enable acessibility service,

on the other hand r3dfox disable at compile accessibility service because mozilla say accessebility service may cause many problems bugs....

i would like to disable accessibility service in firefox and chromium, but i fear the effect on the Native-client, what do you advise me please? should i leave the accessibility service enabled in order to Native client to work normally?

it says some anti-virus have extensions and the accessibility service is necessary....

https://github.com/Eclipse-Community/r3dfox/issues/167#issuecomment-2309002043

**Comment by andy-portmen** [comment]
I don't believe it will have an impact on this extension. You can always experiment though!

**Comment by trimechee** [comment]
We are reassured!! thank you very much!

unfortunately I can't experiment in an ideal way, firefox is using firefox 115 but will soon be updated to firefox 128 in sha Allah, r3dfox disable at compile accessibility service
ac_add_options --disable-accessibility

so impossible to activate accessibility service, luminafox is in beta phase and I prefer to wait
https://github.com/twilight-software/luminafox

and I don't know if accessibility service is disabled in compilation

I discover 2 new browsers based on firefox, but in alpha phase:

https://www.zen-browser.app/

and superfox made by the developer of supermium:

https://github.com/users/win32ss/projects/2

but from my overall impression, it seems that accessibility service does not disrupt the normal operation of native client, thank you very much for your help :) 💯 🥇
