### ISSUE TITLE
Cannot get to work with any Chromium

### ISSUE THREAD

**Issue by dxlr8r** [andy-portmen/native-client#138]
Tested with debian built in, Ungoogled Chronium and Thorium (different  config dir, but I just moved the files over). It seem unable to contact the native client:

```
[6732:6775:0828/211331.510049:WARNING:native_process_launcher.cc(185)] Can't find manifest for native messaging host com.add0n.node
```

It works from Firefox (to Chromium), though. The extension also state: `Log: Specified native messaging host not found.`

**Comment by andy-portmen** [comment]
Most likely the native client cannot find the manifest. Path is not correct. Enable logging to get more info; https://www.chromium.org/for-testers/enable-logging/

**Comment by dxlr8r** [comment]
I did enable logging. This line from first post is from the log:

```
[6732:6775:0828/211331.510049:WARNING:native_process_launcher.cc(185)] Can't find manifest for native messaging host com.add0n.node
```

**Comment by dxlr8r** [comment]
The installer installs to chromium, and yes, for the other two I did copy as well. I also have the same error with "regular" "debian" chromium (which uses `~/.config/chromium`).

Also:

```
$ cat ~/.config/chromium/NativeMessagingHosts/com.add0n.node.json
{
    "name": "com.add0n.node",
    "description": "Node Host for Native Messaging",
    "path": "/home/simen/.config/com.add0n.node/run.sh",
    "type": "stdio",
    "allowed_origins": ...
}
```

```
$ cat /home/simen/.config/com.add0n.node/run.sh
#!/usr/bin/env bash
/usr/bin/node $(dirname "$0")/host.js%
$ which node
/usr/bin/node
```

So to me it seems like everything is in order. I am not browser developer though, but could the shift to manifest v3 be the culprit?

**Comment by andy-portmen** [comment]
I just tried `Ungoogled Chromium` on Debian and it works for me with the default `~/.config/chromium`. Are you trying to connect a developer extension or the official one?

<img width="1115" alt="S1" src="https://github.com/user-attachments/assets/924056af-bb34-42d2-aa4e-66e9d5d6ba2f">

![S2](https://github.com/user-attachments/assets/99215542-9256-45dc-86bf-c3ad08ae3664)

**Comment by dxlr8r** [comment]
All my three Chromiums are clean installs with your extention from the Chrome Store. For Ungoogled Chromium, I dragged and dropped the crx.

https://chromewebstore.google.com/detail/lmeddoobegbaiopohmpmmobpnpjifpii

**Comment by andy-portmen** [comment]
> I dragged and dropped the crx.

What is the extension id? Open the options page and paste the URL here.

**Comment by dxlr8r** [comment]
> > I dragged and dropped the crx.
> 
> What is the extension id? Open the options page and paste the URL here.

chrome-extension://lmeddoobegbaiopohmpmmobpnpjifpii/data/helper-firefox/index.html

I did check that as well. And with the other two, I used Chrome Web Store as I said.

One thing though, I use Sway, and no not have XWayland. So I execute using `--ozone-platform=wayland`. But, it does work with Firefox, and if I remember correct Brave.

**Comment by dxlr8r** [comment]
```
$ strace -yftTe trace=open,read,access -o log  chromium --ozone-platform=wayland
```

```
$ tail -f log | grep ENOENT
16221 09:23:52 access("/etc/chromium/native-messaging-hosts/com.add0n.node.json", F_OK) = -1 ENOENT (No such file or directory) <0.000029>
```

**Comment by dxlr8r** [comment]
After doing:

`cp -R ~/.config/chromium/NativeMessagingHosts/ /etc/chromium/native-messaging-hosts`

It works. Dunno why it does not look in my home dir.

**Comment by dxlr8r** [comment]
After some more digging, I noticed `NativeMessagingUserLevelHosts` being false in:

`/etc/chromium/policies/managed/policies.json`

Setting it to true, it now reads from my home directory.

Also, I did purge and delete chromiums config directories in /etc, so this setting seems to be default for Ungoogled Chromium atleast, might be for others as well.

**Comment by dxlr8r** [comment]
@andy-portmen thanks for help, you can close this case at your convenience. You can follow it up anyway you want, create a feature from it, or just close it and refer to it if anyone else has the issue.
