### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by piroor** [andy-portmen/native-client#15]
Now I'm planning to develop a software very similar to this, but, if it is possible, I hope to use this powerful module as a part of mine instead of writing from scratch. (Of course I hope to do PRs if there is any commonly-useful improvement.)

However, I couldn't find out license terms from this repository. Instead, I've found the term: "This product is released under Mozilla Public License, version 2.0" in your website https://add0n.com/open-in.html 
Does the term affects to codes in this repository and your just forgot to add headers? Or, any other license is applied for this project?

**Comment by andy-portmen** [comment]
Thanks! MPLv2 is added to RP

**Comment by piroor** [comment]
Thank you for the quick response!
