### ISSUE TITLE
[Feature Request] Support Chromium

### ISSUE THREAD

**Issue by cognifloyd** [andy-portmen/native-client#2]
I am using External Application Button to open pages/links in Chrome from Chromium, or in Chromium from Chrome. I am using Linux.

Please add support (by default) for Chromium by installing the native-messaging-hosts file in the chromium specific directory [/etc/chromium/native-messaging-hosts/](https://developer.chrome.com/extensions/nativeMessaging).

I tested by copying /etc/opt/chrome/native-messaging-hosts/ to /etc/chromium/ with success.

**Comment by andy-portmen** [comment]
Can you give 0.2.7 a try and let me know if Chromium is supported or not;
https://github.com/andy-portmen/native-client/releases

**Comment by cognifloyd** [comment]
Yes, this works well (tested with 5a9f58522370e1fbed007c5cc9bb1cc0c61bf9c2 - one commit more than 0.2.7). Thanks for putting it in HOME instead of /etc. That's so much nicer. I had to manually delete the chrome/chromium messaging stuff in /etc, but that's ok. Thanks for making this!
