### ISSUE TITLE
Opening YouTube streams in highest quality

### ISSUE THREAD

**Issue by kocane** [andy-portmen/native-client#21]
Hello.

Nice addon! Exactly what I was looking for. I don't use VLC normally but I guess it'll do (any idea what I would need to do to use MPC? I've tried pointing towards the MPC exe with both the Open in VLC and a custom application with "Open with" but MPC just gives me "failed to render".)

Anyway... it seems like the stream that it opens are not the highest quality (or which ever quality is chosen on the actual YouTube video) but 720p and max 30 FPS, even though the source video has 50/60 FPS in 720p quality.

Anything that can be done for this?

Thanks,

**Comment by andy-portmen** [comment]
VLC is capable of finding playable streams from some web URLs like YouTube. I am not sure if MPC can do the same! That's probably the reason why you get this `failed to render` error.

> it seems like the stream that it opens are not the highest quality

There is no control for this from extension side (or if there is I am not aware of). You may find more info about how VLC handles YouTube links in their forum.

**Comment by kocane** [comment]
@andy-portmen aye.. seems more complicated than just so. Something with any video above 720p, including 720p60 uses "DASH" which is seperate video and audio file, which VLC doesn't really understand.
