### ISSUE TITLE
Open in Edge doesn't work for Firefox

### ISSUE THREAD

**Issue by Sporif** [andy-portmen/native-client#23]
It says it cannot find the native client. I found it's because the extension ID is missing from manifest-firefox.json

I added ` "{94782f74-1a58-4332-a803-00006221a9d0}" ` to `"allowed_extensions"` and it works now.

So I guess you need to add the Open in Edge ID to config.js

**Comment by andy-portmen** [comment]
Thanks! It is fixed on 0.4.4
