### ISSUE TITLE
Source only release

### ISSUE THREAD

**Issue by j605** [andy-portmen/native-client#25]
Can you please make a source only release leaving out the node binary.

**Comment by andy-portmen** [comment]
What is the use case for it as we already have "Source code" in the releases

**Comment by j605** [comment]
Those source code releases include the node binary making them huge.

**Comment by andy-portmen** [comment]
Doesn't seem to work on Linux; https://github.com/andy-portmen/native-client/commit/a52a55a28a7b64c1930790dc6b90016eabf4e56d#diff-50db7bee2fe4f77c2573490079c30bb6R11. I am investigating ...

**Comment by andy-portmen** [comment]
okay it is fixed; https://github.com/andy-portmen/native-client/releases/tag/0.4.6
