### ISSUE TITLE
Interactive batch scripts not visible

### ISSUE THREAD

**Issue by mesvam** [andy-portmen/native-client#28]
When launching batch scripts, the script is launched, but no window is shown. This breaks scripts that require user input.

For an example, save this test script as `test.bat`
```
@echo off
set /p INPUT="Enter some input: "
echo %INPUT%
timeout 3
```
When, launching it normally, the script prompts for input then echo's it back. But when launched via the add-on, the window flashes briefly before disappearing. You can check in a task manager that the process is still running, but the window is not visible.

Is there any way to keep the window visible until the script has finished?

**Comment by andy-portmen** [comment]
instead launch cmd.exe with `/s/c path-of-the-batch-script`

**Comment by mesvam** [comment]
Does it work for you? When I try that using `C:\Windows\System32\cmd.exe` as the executable and `/S /C E:\Temp\test.bat` as the argument, the script does not execute at all.

**Comment by andy-portmen** [comment]
use this in the arguments section: `/s/c c:\\Users\\uname\\Desktop\\example.bat`

**Comment by andy-portmen** [comment]
note the "start" command

**Comment by mesvam** [comment]
Using `start` makes the script work as expected (thanks!), but now the window remains open after the script is finished.

Is there anything that can be changed about how the add-on launches programs? This is becoming a rather clunky solution.

**Comment by andy-portmen** [comment]
> but now the window remains open after the script is finished.

Fix the batch script then
```bat
@echo off
set /p INPUT="Enter some input: "
echo %INPUT%
timeout 3
exit
```

> Is there anything that can be changed about how the add-on launches programs

I am using node's https://nodejs.org/api/child_process.html to launch programs. You can check the native client and play with it to see if there is a better way to do it.

**Comment by mesvam** [comment]
Putting `exit` it in the script means you can't also use it as a command in an interactive prompt, because it will quit your current session.

I took your ideas and modified the workaround to put the exit in the arguments:
Exec: `C:\Windows\System32\cmd.exe`
Arg: `/S /C start C:\\Windows\\System32\\cmd.exe E:\\Temp\\test.bat & exit`

This works as expected so I'll use that for now, but this is still a very awkward solution.
