### ISSUE TITLE
[Feature Request]External Application Button: an option to place all the added application menu items in the main context menu instead of the submenu

### ISSUE THREAD

**Issue by liuxb** [andy-portmen/native-client#31]
Can you please provide an option to place all the added menu items in the main context menu instead of the submenu?
Thanks.

btw: customized context menu icon cant display.

**Comment by andy-portmen** [comment]
> to place all the added menu items in the main context menu instead of the submenu?

Unfortunetly not! WebExtension API has no option to define how menu items are located.

> customized context menu icon cant display.

This is a limitation in the API. I guess for a security reason, browsers only display the actual extension icon for all the items.
