### ISSUE TITLE
Open in VLC - Native client does not exit

### ISSUE THREAD

**Issue by zoidy** [andy-portmen/native-client#32]
On Chromium. The addon successfully launches the native client but when VLC is closed, the native client does not. Opening more videos launches more native client instances that take up resources until the browser is closed.

**Comment by andy-portmen** [comment]
In what OS? So if I have no open instance of VLC and use the extension to send a link to VLC it is not working?

> Opening more videos launches more native client instances

They are supposed to call the VLC executable and then exit.

**Comment by zoidy** [comment]
Guess I should have been more specific from the get go. Sorry about that. OS is Windows 10. 
Opening the link in VLC works. The problem is that closing VLC doesn't close node.exe

Steps:
1. No VLC is currently running. 
2. open a video by right clicking and clicking Open in VLC
3. Video opens and plays correctly. 
![2017-09-08_23-51-07](https://user-images.githubusercontent.com/7082025/30236826-ee031a94-94d7-11e7-889e-db99c045e488.png)
4. Close VLC
5. VLC closes but node.exe remains. 
![strokesplus_2017-09-08_23-51-25](https://user-images.githubusercontent.com/7082025/30236828-f056707a-94d7-11e7-80b1-55aa3a618860.png)





I manually specified the VLC path in the plugin.

**Comment by andy-portmen** [comment]
Thanks for the report. Please wait for the update and recheck. It should be fixed.
