### ISSUE TITLE
[Request] External Application Button support more protocols

### ISSUE THREAD

**Issue by liuxb** [andy-portmen/native-client#33]
when using “on link context”, can external application button support more protocols, such as ed2k://, thunder://,  magnet:? ?
Thanks.

**Comment by andy-portmen** [comment]
Yes, just add the schemes to the pattern text box. Like: `magnet:*, thunder:*, *://*/*`

**Comment by liuxb** [comment]
I added the schemes to the pattern textbox, but the External Application Button context item disappeared.
It seems that External Application Button can only accept the exact value: "*://*/*".
Firefox 56a1, External Application Button 0.2.0
![snap](https://i.imgur.com/hi1qd3G.png)

**Comment by andy-portmen** [comment]
True! I checked this on Chrome. This seems like a bug in Firefox's implementation. Not sure how to fix it.
