### ISSUE TITLE
src_no_node.zip doesn't work on Linux

### ISSUE THREAD

**Issue by lilydjwg** [andy-portmen/native-client#34]
because:

1. it's zip, so no executable bits
2. it's zip, so no symlinks

**Comment by andy-portmen** [comment]
I don't see why it is not working on Linux. Zip supports both; https://github.com/andy-portmen/native-client/blob/master/prepare.sh#L11

What is your distribution?

**Comment by lilydjwg** [comment]
I'm on Arch Linux.

And yes, the unzip program supports both, but not 7z. Python's zipfile module doesn't can see them but not extract using them.
