### ISSUE TITLE
add support to open in "safari technology preview"

### ISSUE THREAD

**Issue by justlaputa** [andy-portmen/native-client#36]
Hi, I found the chrome extension "Open in Safari", does not support setting Safari exec path.

I'm using "Safari Technology Preview", and I hope I can use the chrome extension to open tab in "Safari Technology Preview" instead of safari. Is it possible to add an option of this?

Thanks!

**Comment by andy-portmen** [comment]
Is it possible to call the "safari technology preview" using the `open` command?

**Comment by justlaputa** [comment]
yes, it is. I tried it in my terminal it works.
```
# both of these works
$ open -a "Safari Technology Preview"
$ open -a "safari technology preview" 
```

actually I tried to modify the file `config.js` in my chrome extension folder, chrome will show `extension maybe corrupted`. So I could not do it.

**Comment by andy-portmen** [comment]
Sounds good. As of the next release, you can define a custom application name in the options page to have a command like `open -a "app name" url`
