### ISSUE TITLE
[External Application Bundle] - Little Problem

### ISSUE THREAD

**Issue by cyberpunkbln** [andy-portmen/native-client#39]
Hello,

in this application i have the problem, that when a program (youtube-dl) calls another second program (ffmpeg), the second program popup in a new cmd-window. That disturbs.

Give it a trick or an choice in the addon, that this popup came minimized or in the background like the called mother-tasks? An option that i can encapsulate the called mother-prg in a root-prg? or so?

thx

**Comment by andy-portmen** [comment]
Shouldn't the first executable handles this correctly?

**Comment by cyberpunkbln** [comment]
Hi,

yes the first exe (i call this the mother-exe :)) handles it correctly, but when this mother-exe calls a daugter-exe a rough-window-shell (cmd) popup with the raw called name (youtube-dl -> extract or convert audiostreams calls ffmpeg.exe).

I think the daugter-exe cannot handle an call without an cli-cmd around the hole process. When i call this in a cmd or powershell terminal then its don't popup why a terminal is there thats handle that ouput.

I test with a small call.cmd to handle this with a call that only popup once. But it will be great when it gives a solution in the application.

**Comment by cyberpunkbln** [comment]
Is it possible to bring an option to call an Program within an terminal (on windows cmd,powershell)? A pre called Program so i say.

**Comment by andy-portmen** [comment]
FAQ10 maybe? https://add0n.com/external-application-button.html

**Comment by cyberpunkbln** [comment]
Hello,
yes was an option but then not cmd.exe compatible escaping of signs ala ampersand and with faq10 i cannot deliver youtube-playlist[HREF].

**Comment by andy-portmen** [comment]
I am not following. Please explain what exactly you want to do

**Comment by cyberpunkbln** [comment]
Oh sorry i have read this answer before the others, your last update resolve this problem,too :) .
