### ISSUE TITLE
Open m3u8 stream in VLC

### ISSUE THREAD

**Issue by midas02** [andy-portmen/native-client#4]
Hello, is the "open to VLC" extension meant to be able to be grabbing m3u8 streams from a webpage as well? Or is this action being deferred to VLC, and is the extension merely passing on the webpage's URL to VLC?

Also, I've just written a new decryptor for VLC, so "open in VLC" should start handling those links as well. Could you tell me where that modification needs to be made, as I've been browsing through the code, and couldn't find it?

Thanks!

**Comment by andy-portmen** [comment]
> Hello, is the "open to VLC" extension meant to be able to be grabbing m3u8 streams from a webpage as well?

Well, open in VLC has two methods of grabbing media sources. One from right click context menu over video and audio elements. In this case if audio and video file allow access to the media source an icon is displayed. Like what we have in https://www.w3schools.com/html/html5_video.asp

The second method which is just introduced in version 0.1.3, is to grab media files from WebRequest. In this case the toolbar button is activated once a media source is detected.

>  grabbing m3u8 streams

Is there any link to access this m3u8 streams?

> Also, I've just written a new decryptor for VLC, so "open in VLC" should start handling those links as well

Can you provide more info. Is this a VLC extension or browser extension? How does it work and what is expected from Open in VLC extension?
