### ISSUE TITLE
[External Application Bundle] Problem with Quotes on Parameters and Spaces

### ISSUE THREAD

**Issue by cyberpunkbln** [andy-portmen/native-client#40]
Hello,

i want to try to give an cmd-batch this

-f bestaudio -x --audio-format mp3 -o "%UserProfile%\Music\Youtube-DL\%(title)s.%(ext)s" [HREF] --write-all-thumbnails

an exe became the excact path but the command not. ^" don't work

what must i type that %7=path_with_spaces?

thx

**Comment by andy-portmen** [comment]
Try 

```
-f bestaudio -x --audio-format mp3 -o "'%UserProfile%\Music\Youtube-DL%(title)s.%(ext)s'" [HREF] --write-all-thumbnails
```

as of suggested by https://add0n.com/external-application-button.html#IDComment1049753154

**Comment by andy-portmen** [comment]
https://add0n.com/external-application-button.html#faq14

**Comment by cyberpunkbln** [comment]
Hi,
yes cool but this is only for PowerShell-Skripting (.ps), the old cli cmd.exe (.cmd,.bat) don't encapsulate strings with spaces in one string.

**Comment by cyberpunkbln** [comment]
I catch the %* for the whole Argument-String-Param i must say. The Arg-Params can be different.

**Comment by cyberpunkbln** [comment]
Now i have tried to use a cmd to call a pscript or directly the powershell

encapsulate single with double quotes "'[HREF'" functioned

powershell -Command %~dp0\youtube-dl.exe %*

but i have the problem too, ampersand will not be escaped right

for dos he must ^& so escaped

i will use dos as an container fpr the pscript or powershell command why here on this pc i don't can set the execution policy

**Comment by andy-portmen** [comment]
[quotes.zip](https://github.com/andy-portmen/native-client/files/1326767/quotes.zip)

Try this dev version. There is a new option in the settings to include quotations in the argument list. Let me know if you are not familiar with how to install dev versions.

**Comment by cyberpunkbln** [comment]
Hello,
thx i will try it and leave a comment.

**Comment by cyberpunkbln** [comment]
Hi,

so i have seen your last Public-Update has this feature and it's functioned very very well, when i put doublequotes around [HREF] and use the option, the whole Path will be delivered with a double quote surround. Great.

Now i must write again my cmd-scripts and iam happy.

thx
