### ISSUE TITLE
[External Application Bundle - Feature Request] SubMenu and manual sorting

### ISSUE THREAD

**Issue by cyberpunkbln** [andy-portmen/native-client#41]
Hello,

only a little Feature Request while i work with your AddOn and youtube-dl. I use for every situation a new Context-Menu and it will be great if it possible that i can have SubMenus in the Context-Menus. Like Sento -> Youtube-DL -> Video -> no playlist,playlist and so on.

Is it possible to sort manually the entrys?

It is possible to make Placement wit more than one Placement so that i dont must for every placement one piece of placement?

thx

ps: Is a little bit confusing about the source and the AddOns? Where are the sources from the your webapps that uses native-client here on github?

**Comment by andy-portmen** [comment]
> It is possible to make Placement wit more than one Placement so that i dont must for every placement one piece of placement?

Yes, as of the next release.

> ps: Is a little bit confusing about the source and the AddOns? Where are the sources from the your webapps that uses native-client here on github?

EAB now has its own GitHub; https://github.com/andy-portmen/external-application-button/

> it will be great if it possible that i can have SubMenus in the Context-Menus

I think this is possible but since it makes the UI of the options page very complex, at least at the moment I don't have time to do this. Pull requests are welcome!

**Comment by cyberpunkbln** [comment]
Thx for the Repo and the future Features.
