### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by RayVonCore** [andy-portmen/native-client#47]
Hello, Cant seem to install on windows10 and ff56. check connection = cannot find native client. any advice would be gratefully

**Comment by andy-portmen** [comment]
Do you get any error while installing the "install.bat"?

**Comment by RayVonCore** [comment]
Nope

**Comment by RayVonCore** [comment]
App ready and press any key comes up ok

**Comment by RayVonCore** [comment]
.. Writting to Chrome Registry
.. Key: HKCU\Software\Google\Chrome\NativeMessagingHosts\com.add0n.node
The operation completed successfully.
.. Writting to Firefox Registry
.. Key: HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.add0n.node
The operation completed successfully.
.. Chrome Browser is supported
.. Firefox Browser is supported
.. Native Host is installed in C:\

>>> Application is ready to use <<<


Press any key to continue . . .

**Comment by andy-portmen** [comment]
did you trim this line?
`Native Host is installed in C:\`

**Comment by RayVonCore** [comment]
yes

**Comment by RayVonCore** [comment]
lazy copy and paste. Have installed on a different  pc  with no problems.

**Comment by RayVonCore** [comment]
Chrome has the same problem.

**Comment by andy-portmen** [comment]
What is your Windows version?

**Comment by RayVonCore** [comment]
windows 10 pro

**Comment by RayVonCore** [comment]
version1607

**Comment by andy-portmen** [comment]
So you get the installation page when you click on the button? and that check button reports error?

**Comment by RayVonCore** [comment]
Cannot find native client is what pops up after the check

**Comment by andy-portmen** [comment]
Everything looks okay. Maybe there is a problem with the attached NodeJS. Please open the node directory then open a "cmd.exe" at the root. Run "node.exe -v" and see what you get

**Comment by RayVonCore** [comment]
> node.exe -v
ReferenceError: node is not defined
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)

**Comment by andy-portmen** [comment]
Seems like NodeJS is working too!
https://stackoverflow.com/questions/27170037/first-time-using-node-js-referenceerror-node-is-not-defined

**Comment by RayVonCore** [comment]
I've installed node.js v8.6.0.  and node -v now shows v. 

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Flav>node -v
v8.6.0
-------------------------------------

One last step 
Install.bat gives back >>>
.. Writting to Chrome Registry
.. Key: HKCU\Software\Google\Chrome\NativeMessagingHosts\com.add0n.node
The operation completed successfully.
.. Writting to Firefox Registry
.. Key: HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.add0n.node
The operation completed successfully.
.. Chrome Browser is supported
.. Firefox Browser is supported
.. Native Host is installed in C:\Users\Flav\AppData\Local\com.add0n.node

>>> Application is ready to use <<<

Press any key to continue . . .

the Extract the downloaded package in a local directory and  Now double-click the install.bat file aren't crossed out like download here line tho.
--------------------------------

check connection still gives back cant find native client .

Balls ha

**Comment by RayVonCore** [comment]
um ere not sure why some text is in bold !

**Comment by andy-portmen** [comment]
If you are willing to share a teamviewer session, I can check the installation and hopefully find a solution!

**Comment by cubedj** [comment]
isn't with your native client installed **node v6.11.0**? ...

**Comment by andy-portmen** [comment]
@cubedj yes, the included NodeJS is v6.11.0

**Comment by RayVonCore** [comment]
Reinstalling windows 10 fix it ha. Thanks for your time tho !
