### ISSUE TITLE
[Feature Request] Auto-close the current (the origins') tab

### ISSUE THREAD

**Issue by russell1215** [andy-portmen/native-client#48]
if I'm in (From) BrowserA (origin)  & I 'push' a tab (To) BrowserB (destination)
= auto-close that tab from BrowserA (origin).  

If I'm in (From) Chrome (origin) & I 'push' a tab (To) FireFox (destination)
= auto-close that tab from Chrome (origin).

**Comment by andy-portmen** [comment]
Thanks for the feedback. Will have this on the next release.
