### ISSUE TITLE
install.sh installs the Native Host direcly under $HOME

### ISSUE THREAD

**Issue by halloleo** [andy-portmen/native-client#5]
When I run `./install.sh` it copy the Native Host into a directory `$HOME/com.add0n.node` - i.e. directly under my home directory - Cluttering my home directory with visible directories is not desirable. Can the Native Host get installed into `$HOME/bin`? And how?

**Comment by andy-portmen** [comment]
why not using `./install.sh --custom-dir=~/custom_dir_here` then?

**Comment by AJCxZ0** [comment]
Thanks for the tip.

I saw no mention of the --custom-dir option in the instructions, documentation or in install.sh and it's great to have that option, but may I suggest a more appropriate default than $HOME? Perhaps ~/.config or maybe something under ~/.local would be appropriate for almost all modern Linux desktop environments.

**Comment by andy-portmen** [comment]
#42
