### ISSUE TITLE
No luck on waterfox

### ISSUE THREAD

**Issue by HaoZeke** [andy-portmen/native-client#62]
Using `node v10` there doesn't seem to be any effect.

```bash
./install.sh            
/$HOME/.nvm/versions/node/v10.0.0/bin/node
NodeJS status = 0
Installer is using your system NodeJS.
 -> Root directory is /home/haozeke/.config
 -> Creating a directory at /home/haozeke/.config/google-chrome/NativeMessagingHosts
 -> Chrome Browser is supported
 -> Creating a directory at /home/haozeke/.config/chromium/NativeMessagingHosts
 -> Chromium Browser is supported
 -> Creating a directory at /home/haozeke/.config/vivaldi/NativeMessagingHosts
 -> Vivaldi Browser is supported
 -> Creating a directory at /home/haozeke/.mozilla/native-messaging-hosts
 -> Firefox Browser is supported
 -> Creating a directory at /home/haozeke/.config/com.add0n.node
 => Native Host is installed in /home/haozeke/.config/com.add0n.node


>>> Application is ready to use <<<

```

I still get the native client is not installed error. 

```bash
$HOME/.config/com.add0n.node/run.sh   
(node:18867) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
^C
```

Here are the waterfox logs:

![nativeclientbug](https://user-images.githubusercontent.com/4336207/39385798-7b120d74-4a8f-11e8-9ad1-7a962f86a1ad.png)

Also, system details: 
![neofetch-2018-04-28-02-50-40-25639](https://user-images.githubusercontent.com/4336207/39385677-1a58fff6-4a8f-11e8-8ffa-ac036ae86ec4.png)

**Comment by HaoZeke** [comment]
Thanks! I left `waterfox` for this, glad to go back to it.

**Comment by grahamperrin** [comment]
Please: 

- where is `native-messaging-hosts` on Windows 10? 

I can't find it (I looked at a variety of likely paths); neither can File Explorer. 

Background (Waterfox Current 68.0b1): 

- https://redd.it/d43hjc

**Comment by mmaximo** [comment]
Hello, Sorry for bumping up this issue, but in case someone is looking for a solution for this problem, I solved it in Windows by exporting by exporting the registry key ` HKCU\SOFTWARE\Mozilla\NativeMessagingHosts`, replaced Mozilla with Waterfox and then importing it back.
