### ISSUE TITLE
Browser console errors for Open with Vivaldi

### ISSUE THREAD

**Issue by siffegh** [andy-portmen/native-client#63]
Hi, I'm getting these errors for Open with Vivaldi on every page load. Sometimes there are only one, sometimes several:

prefs is undefined    inject.js:20
<anonymous>    moz-extension://9b5e74aa-89e0-42e9-b195-04dd4a9c6590/data/inject.js:20:23
	apply    self-hosted:4291:5
	applySafeWithoutClone    resource://gre/modules/ExtensionCommon.jsm:304:16
	wrapPromise/</<    resource://gre/modules/ExtensionCommon.jsm:517:15
	withLastError    resource://gre/modules/ExtensionCommon.jsm:441:14
	wrapPromise/<    resource://gre/modules/ExtensionCommon.jsm:509:11

**Comment by andy-portmen** [comment]
Sorry for the very late reply. I think this is an internal FF issue with the managed storage API. Anyhow, I am going to double check the preferences existence to hopefully get rid of the error. Please reopen if you get the error after the next update.
