### ISSUE TITLE
can't work well on firefox 61.01 and 56.02

### ISSUE THREAD

**Issue by truelv** [andy-portmen/native-client#66]
I have done as the video on youtube tells. the step of checking connection is all right but still jump to moz-extension://e1eb11bf-4118-4d47-80d9-a9192f4f22ce/data/helper/index.html

**Comment by andy-portmen** [comment]
What is the extension name? Are you sure the executable is reachable?

**Comment by truelv** [comment]
firefox extension : Open in Tor Browser 0.1.1  

I just download windows.zip and execute install.bat  then  I push check connection . On the bottom of my desktop comes up a dialog says Native client vesion is 0.6.7 . That is all I have done. Do I need set advanced settings and change path?

**Comment by andy-portmen** [comment]
You are almost done. Just go to the options page and set the path to the tor browser. since the tor browser is portable, the extension cannot find it!

**Comment by truelv** [comment]
Well done. It is solved as you say. Thx a lot , buddy.
