### ISSUE TITLE
do I have to install IE browser first?

### ISSUE THREAD

**Issue by hsdchenliyang** [andy-portmen/native-client#67]
I use firefox and chromium on linux ,and   I need to  open a video webpage which  can only be  opened  on IE. however I don't want to install IE in my computer. Does this plug-in helpful?

**Comment by andy-portmen** [comment]
No, unfortunately not. This extension only calls the external executable which in your case is the IE. You may use websites that emulate IE like https://ieonchrome.com/ or you can install IE with wine.

**Comment by hsdchenliyang** [comment]
Thanks
