### ISSUE TITLE
Baidu	Win32.Trojan.WisdomEyes.16070401.9500.9994

### ISSUE THREAD

**Issue by blackweta** [andy-portmen/native-client#68]
windows.zip file hash identified by Baidu antivirus (via VirusTotal uploader)as  Malware  Win32.Trojan.WisdomEyes.16070401.9500.9994
File location:https://github.com/andy-portmen/native-client/releases

https://www.uninstallvirusmalware.com/quick-steps-to-get-rid-of-win32-trojan-wisdomeyes-16070401-9500-9993-from-windows-xp
-- | --

**Comment by andy-portmen** [comment]
Here is the report I get for https://www.virustotal.com/#/url/f3f3d029389e90341a38293e350ba8869633e1d6b6afe87d8ed692352722c8c4/detection

**Comment by blackweta** [comment]
Here's the report I get :

**Comment by blackweta** [comment]
Here's my report: (Didnt realise the urls were sharable.

https://www.virustotal.com/en/file/ec7ebc56cb831786da8d9d3d59d7d8845db0297d2c745c62f374801d62b4ce61/analysis/1532908534/


Baidu | Win32.Trojan.WisdomEyes.16070401.9500.9994
-- | --

**Comment by andy-portmen** [comment]
You should use the original file not the modified one. Do not download the file as it might get affected. Just pass the URL to virustotal.com. It will fetch the file and examine it. btw, the only executable in this package is the **official** NodeJS executable (this can be confirmed by checking the HASH code).

You can also download a fresh copy of NodeJS and replace it then run the `install.bat` file if you prefer so.
