### ISSUE TITLE
sharepoint open in adobe reader bug

### ISSUE THREAD

**Issue by josy1024** [andy-portmen/native-client#70]
when opening a document from sharepoint the search parameter is added and acrobat could not find the document directly (without download)

SEARCH does not work
https://tenant.sharepoint.com/sites/site/doc/filename.pdf#search=

WORKS
https://tenant.sharepoint.com/sites/site/doc/filename.pdf

**Comment by andy-portmen** [comment]
Thanks! will be fixed on the latest release
