### ISSUE TITLE
Firefox extension corrupt (External Application Button)

### ISSUE THREAD

**Issue by BlueMax** [andy-portmen/native-client#8]
Hallo,
when i try to install the [addon](https://addons.mozilla.org/de/firefox/addon/external-application/) with Firefox it says addon is corrupt and cannot be installed.
Any ideas?

Firefox 53 (64bit)
Arch Linux

**Comment by andy-portmen** [comment]
This should be fixed with the next release. I have already submitted a fix and still waiting for review.

**Comment by BlueMax** [comment]
0.1.6 now available. Installs properly on Fx 53.0.3.
Problem solved. Thanks!
