### ISSUE TITLE
Can't seem to get the target pattern to work with magnet links

### ISSUE THREAD

**Issue by DutchPlays** [andy-portmen/native-client#85]
I've been trying to add peerflix to External Application Button, but the target pattern doesn't seem to work properly with magnet links. When I right click on a magnet link, the option to open it in an external application isn't shown. When I change the `href` to a dummy magnet link, like `magnet:test`, then the external application does show up.
I've also tried setting the pattern to `magnet:?xt=urn:btih:*`, which also didn't work.
![Settings](https://user-images.githubusercontent.com/16637577/78252146-ace7c700-74f2-11ea-8b7a-8242adc39828.png)
![Href](https://user-images.githubusercontent.com/16637577/78252143-ac4f3080-74f2-11ea-82ba-0428b60ba78b.png)
![Context](https://user-images.githubusercontent.com/16637577/78252141-abb69a00-74f2-11ea-9cf9-bc72027a577a.png)

**Comment by andy-portmen** [comment]
I don't see any doc related to these types of matching; https://developer.chrome.com/apps/match_patterns

I would say use `<all_urls>` for the target pattern and then limit the page pattern to specific pages

**Comment by DutchPlays** [comment]
That's what I ended up doing. Would it be possible to add some sort of blacklist so that I could blacklist all HTTP and HTTPS urls?

**Comment by andy-portmen** [comment]
I don't think so. The API only allows specifying target and document filters.

**Comment by DutchPlays** [comment]
In that case, I guess it just isn't possible. Thanks for trying to help.
