### ISSUE TITLE
Instructions are misleading

### ISSUE THREAD

**Issue by Calorion** [andy-portmen/native-client#99]
The last step [installation instructions](moz-extension://9d61ad54-3a04-4644-a8bf-28678f02d9c9/data/helper/index.html) says to "Now open a terminal in the root directory and run ./install.sh."

But the root directory is, of course, "/". Running ./install.sh from the root directory, unless you happened to put install.sh there, will do nothing.

**Comment by andy-portmen** [comment]
That's right. I am gradually porting the extensions to their unique instruction. Will get fixed by upcoming updates. Thanks for the report.
